
/**
 * @file    error.h
 * @brief   error-reporting subsystem for tracking and bubbling failures
 */


#pragma once
#ifndef ERROR_H
#define ERROR_H


#include    "common.h"

#include    "os.h"


#define     TSALLOC_NO_ERROR_CONTEXT    (-1)


#ifndef     TSALLOC_ERROR_DEFINED
#define     TSALLOC_ERROR_DEFINED

    /*
    * @enum    TSALLOC_ERROR
    * @brief   status codes representing the outcome of allocator operations
    */
    enum TSALLOC_ERROR    : uint8_t
    {
        TSALLOC_SUCCESS = 0,        ///< operation completed successfully
        TSALLOC_UNTRACKED_FAILURE,  ///< arena failed to initialize/deinitialize
        TSALLOC_OS_ERR,             ///< os error, sets `os_error_code`
        TSALLOC_AUXIL_MAP_ERR,      ///< auxilliary allocator could not allocate memory
        TSALLOC_AUXIL_UNMAP_ERR,    ///< auxilliary allocator could not free memory
        TSALLOC_AUXIL_MADVISE_ERR,  ///< auxilliary madvise could not implement flag
        TSALLOC_INVALID_ARGS        ///< invalid arguments passed as parameters
    }; 
    typedef enum TSALLOC_ERROR  ts_err_t;
    
    
    struct ts_error_state
    {
        const char *trace;              ///< set only if TSALLOC is compiled with OPT_TRACE_ERRORS enabled
        const char *message;            ///< error message set by TSALLOC
        int         os_error_code;      ///< error code set by OS
        ts_err_t    ts_error_code;      ///< error code set by TSALLOC
    };
    typedef struct ts_error_state   ts_errstate_t;

#endif      //TSALLOC_ERROR_DEFINED


typedef struct tsalloc_global_arena glob_t; 


void 
_ts_req_errstate(
    ts_errstate_t  *state,
    int32_t         glob_uid
);

void 
_set_tsalloc_error(
    const char *orig_filename,
    const char *message,
    int32_t     glob_uid,
    int         os_error_code,
    ts_err_t    ts_error_code,
    uint16_t    orig_line
);


#define _SET_TSALLOC_ERROR_IMPLICIT_OS( \
    glob_uid,                           \
    message,                            \
    ts_error_code                       \
) do                                    \
{                                       \
    _set_tsalloc_error                  \
    (                                   \
        __FILE__,                       \
        (message),                      \
        (glob_uid),                     \
        sys_error_code(),               \
        (ts_error_code),                \
        __LINE__                        \
    );                                  \
} while (false)

#define _SET_TSALLOC_ERROR_EXPLICIT_OS( \
    glob_uid,                           \
    message,                            \
    ts_error_code,                      \
    os_error_code                       \
) do                                    \
{                                       \
    _set_tsalloc_error                  \
    (                                   \
        __FILE__,                       \
        (message),                      \
        (glob_uid),                     \
        (os_error_code),                \
        (ts_error_code),                \
        __LINE__                        \
    );                                  \
} while (false)

#define _SET_TSALLOC_ERROR_DISPATCH(    \
    _1,                                 \
    _2,                                 \
    _3,                                 \
    _4,                                 \
    FUNC,                               \
    ...                                 \
) FUNC

/**
 * @brief   instantly captures the file, line, and reason for a failure
 * 
 * evaluates to a safe `do-while(false)` block. mutates the context's pinned error struct in-place
 * 
 * @param   glob_uid        global uid of corresponding `glob_t` instance
 * @param   message         constant string literal detailing what broke
 * @param   ts_error_code  `ts_err_t` value representing reason of failure
 * @param   os_error_code   [optional argument] `int` error-code generated by os pertaining to
 *                          reason of failure
 * 
 * @warning must be called precisely when the initial error occurs, not during bubbling
 */
#define set_tsalloc_error(...)          \
    _SET_TSALLOC_ERROR_DISPATCH(        \
        __VA_ARGS__,                    \
        _SET_TSALLOC_ERROR_EXPLICIT_OS, \
        _SET_TSALLOC_ERROR_IMPLICIT_OS  \
    ) (__VA_ARGS__)


#ifdef      OPT_TRACE_ERRORS

    void 
    _append_tsalloc_error_trace(
        const char *orig_filename,
        const char *orig_function,
        int32_t     glob_uid
    );

    /**
     * @brief   appends the current function to the error breadcrumb trail
     * 
     * used exclusively when bubbling an existing error upward. safely writes to the internal trace 
     * buffer without dynamic allocation
     * 
     * @param   glob_uid    global uid of corresponding `glob_t` instance
     */
    #define append_tsalloc_error_trace(     \
        glob_uid                            \
    ) do                                    \
    {                                       \
        _append_tsalloc_error_trace         \
        (                                   \
            __FILE__,                       \
            __func__,                       \
            glob_uid                        \
        );                                  \
    } while (false)
#else
    #define append_tsalloc_error_trace(     \
        glob_uid                            \
    ) ((void)0)
    
#endif      // TRACE_ERRORS


#endif  // ERROR_H